// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GenerateIntegers(arg1) {
  return window['go']['control']['QrngCli']['GenerateIntegers'](arg1);
}

export function GenerateKeys(arg1, arg2) {
  return window['go']['control']['QrngCli']['GenerateKeys'](arg1, arg2);
}

export function GenerateSha256(arg1, arg2) {
  return window['go']['control']['QrngCli']['GenerateSha256'](arg1, arg2);
}

export function GetRatio() {
  return window['go']['control']['QrngCli']['GetRatio']();
}

export function GetSpeed() {
  return window['go']['control']['QrngCli']['GetSpeed']();
}

export function GetSummary() {
  return window['go']['control']['QrngCli']['GetSummary']();
}

export function GetUsbDevices() {
  return window['go']['control']['QrngCli']['GetUsbDevices']();
}
