// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GenerateIntegers(arg1:number):Promise<Array<string>>;

export function GenerateKeys(arg1:number,arg2:number):Promise<Array<string>>;

export function GenerateSha256(arg1:number,arg2:number):Promise<Array<string>>;

export function GetRatio():Promise<string>;

export function GetSpeed():Promise<string>;

export function GetSummary():Promise<string>;

export function GetUsbDevices():Promise<Array<string>>;
